### ISSUE TITLE
[Bug]: SM70 default TileLang prefill fails to compile with tilelang==0.1.9

### ISSUE THREAD

**Issue by Leonccaa** [1CatAI/1Cat-vLLM-0.0.1#105]
### Summary

On V100 / SM70, the default FlashQLA TileLang GDN prefill route in the 1Cat-vLLM 1.2.2 stack deterministically fails at JIT compilation.

The immediate cause is the pinned `tilelang==0.1.9`. Its CUDA header has a broken BF16 fallback for `__CUDA_ARCH__ < 800`: `common.h:778` passes `__nv_bfloat16` values to the half-only intrinsic `__hfma`.

### Environment

- 1Cat-vLLM 1.2.2 wheel / CUDA 12.8 image
- Python 3.12, CUDA toolkit 12.8.93
- 2 x Tesla V100 32 GB (compute capability 7.0), TP=2
- `tilelang==0.1.9`
- Qwen3.6-27B AWQ hybrid GDN model
- `gdn_prefill_backend=flashqla_sm70`
- `VLLM_SM70_FLASHQLA_ORIGINAL_PREFILL` left unset (the current code defaults it to the original TileLang route)

The repository currently pins both `apache-tvm-ffi==0.1.9` and `tilelang==0.1.9` in [requirements/cuda.txt](https://github.com/1CatAI/1Cat-vLLM/blob/644d8a7cd05ed4ecd1cd188e3c05b4bbd074f504/requirements/cuda.txt).

### Actual result

The first GDN prefill warmup / request selects the original SM70 TileLang path and tries to JIT `tilelang_chunk_local_cumsum_kernel` with `nvcc -arch=sm_70`. Compilation then fails at:

```text
.../tilelang/src/tl_templates/cuda/common.h(778): error:
no suitable user-defined conversion from "__nv_bfloat16" to "__half" exists

return __nv_bfloat162{
    __hfma(a.x, b.x, c.x), __hfma(a.y, b.y, c.y)
};
```

This is not caused by the model using BF16. The first failing generated kernel has only `int*` and `float*` parameters; merely including this TileLang header causes the SM70 compilation failure.

### Minimal reproduction

No model or GPU is required. In a fresh container with TileLang 0.1.9, compile any CUDA file which includes the header, for example:

```cuda
#include <tl_templates/cuda/common.h>

extern "C" __global__ void int_float_only(const int* input, float* output) {
    if (threadIdx.x == 0) output[0] = static_cast<float>(input[0]);
}
```

with the same include roots used by TileLang JIT:

```bash
nvcc --cubin -O3 -lineinfo -arch=sm_70 -std=c++17 \
  -I.../site-packages/tilelang/src \
  -I.../site-packages/tilelang/3rdparty/cutlass/include \
  -o int_float_only.cubin int_float_only.cu
```

It exits with the six `common.h:778` conversion errors above.

### Upstream status and validation

This exact fallback was fixed upstream in TileLang v0.1.10. Compare:

- [v0.1.9 common.h](https://raw.githubusercontent.com/tile-ai/tilelang/v0.1.9/src/tl_templates/cuda/common.h)
- [v0.1.10 common.h](https://raw.githubusercontent.com/tile-ai/tilelang/v0.1.10/src/tl_templates/cuda/common.h)

The newer implementation converts BF16 lanes to float, performs the arithmetic, then converts back to BF16.

We validated this in a separate fresh container by changing only that upstream fallback in the container's writable layer: the identical minimal `sm_70` compilation changed from exit code 1 to exit code 0. No existing service, model mount, or cache was modified.

### Requested fix

Could 1Cat please either:

1. update the compatible TileLang / apache-tvm-ffi dependency pair to a version including the v0.1.10 fix, or
2. cherry-pick the small upstream `common.h` fallback fix into the packaged dependency?

Please also add a small SM70 JIT smoke test that includes `tl_templates/cuda/common.h`, so this path is covered by the V100 release validation.

### Temporary workarounds

- set `VLLM_SM70_FLASHQLA_ORIGINAL_PREFILL=0` to use the compiled VLK varlen implementation, or
- select the Triton GDN prefill backend.

Could you also confirm which GDN prefill backend was used for the official V100 validation of this release?

**Comment by Zephyr69** [comment]
+1, which crashes the engine at the first request.

**Comment by Fasiany** [comment]
same problem to me

**Comment by JGaed** [comment]
same here

**Comment by splendiz** [comment]
same problem ：（

**Comment by DSYZayn** [comment]
same problem

**Comment by slash-spb** [comment]
The same(((

**Comment by yangzhuxinyzx** [comment]
已定位并修复：TileLang 0.1.9 在 SM70 generated header 中生成无效的 BF16 到 half __hfma 调用。Draft PR: https://github.com/1CatAI/1Cat-vLLM/pull/116 。该 PR 将 TileLang/apache-tvm-ffi 固定到 0.1.10，并加入离线 SM70 CUBIN 编译回归。物理 V100 worker 启动仍是合并前门禁。

**Comment by chtaihei-ust-hk** [comment]
Verified the fix independently: with the 1.2.2 wheel (tilelang==0.1.9) a Qwen3.8-27B NVFP4 startup fails deterministically at TileLang JIT with the same `__nv_bfloat162`/`__hfma` errors (6 errors in tvm_kernels.cu, sm_70). Upgrading to `tilelang==0.1.10` + `apache-tvm-ffi==0.1.10` resolves it — service starts clean. +1 for #116.

Additional context from a from-source main build (af7708366): Qwen3.8-27B-NVFP4 TP2 @ 200k works end-to-end (v1.2.2 hangs at 196608 on both stock and patched paths; main's FA_V100 long-context fixes resolve it). Controlled decode A/B (llama-benchy tg256, 0→196608 sweep): custom small-M backend vs stock TurboMind — 57.3 vs 34.0 t/s at depth 0, 23.0 vs 15.8 at 196608 (+46% at 200k); prefill converges to ~358 t/s at 200k on both.
