### ISSUE TITLE
[Bug]: Prebuilt wheel fails on Ubuntu 26.04 (glibc 2.41):  tilelang JIT compilation fails with CUDA 12.8 math header conflicts

### ISSUE THREAD

**Issue by turbo2ltr** [1CatAI/1Cat-vLLM-0.0.1#626]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
uv is set
==============================
        System Info
==============================
OS                           : Ubuntu 26.04 LTS (x86_64)
GCC version                  : (Ubuntu 14.3.0-14ubuntu1) 14.3.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.43

==============================
       PyTorch Info
==============================
PyTorch version              : 2.10.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A
XPU used to build PyTorch    : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.14 (main, Sep  1 2026, 14:16:52) [Clang 22.1.3 ] (64-bit runtime)
Python platform              : Linux-7.0.0-31-generic-x86_64-with-glibc2.43
    
==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: Tesla PG500-216
GPU 1: Tesla PG500-216
GPU 2: Tesla P40
GPU 3: Tesla P40

Nvidia driver version        : 580.178.04
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           46 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  72
On-line CPU(s) list:                     0-71
Vendor ID:                               GenuineIntel
Model name:                              Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
CPU family:                              6
Model:                                   63
Thread(s) per core:                      2
Core(s) per socket:                      18
Socket(s):                               2
Stepping:                                2
CPU(s) scaling MHz:                      61%
CPU max MHz:                             2300.0000
CPU min MHz:                             1200.0000
BogoMIPS:                                4599.96
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm arat pln pts vnmi md_clear flush_l1d
Virtualization:                          VT-x
L1d cache:                               1.1 MiB (36 instances)
L1i cache:                               1.1 MiB (36 instances)
L2 cache:                                9 MiB (36 instances)
L3 cache:                                90 MiB (2 instances)
NUMA node(s):                            2
NUMA node0 CPU(s):                       0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70
NUMA node1 CPU(s):                       1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             KVM: Mitigation: Split huge pages
Vulnerability L1tf:                      Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                       Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:                  Mitigation; PTI
Vulnerability Mmio stale data:           Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Old microcode:             Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.6.11.post2
[pip3] numpy==2.3.5
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cccl-cu12==12.9.27
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvcc-cu12==12.9.86
[pip3] nvidia-cuda-nvdisasm==13.4.49
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.18.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.7.0
[pip3] nvidia-cutlass-dsl-libs-base==4.7.0
[pip3] nvidia-cutlass-dsl-libs-core==4.7.0
[pip3] nvidia-cutlass-dsl-libs-cu12==4.7.0
[pip3] nvidia-ml-py==13.610.43
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.4.5
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.2.0
[pip3] torch==2.10.0
[pip3] torch-c-dlpack-ext==0.1.5
[pip3] torchaudio==2.10.0
[pip3] torchvision==0.25.0
[pip3] transformers==5.17.0
[pip3] triton==3.6.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 1.5.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; XPU: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PIX     PIX     0,2,4,6,8,10    0               N/A
GPU1    PIX      X      PIX     PIX     0,2,4,6,8,10    0               N/A
GPU2    PIX     PIX      X      PIX     0,2,4,6,8,10    0               N/A
GPU3    PIX     PIX     PIX      X      0,2,4,6,8,10    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
CUDA_DEVICE_ORDER=PCI_BUS_ID
CUDAHOSTCXX=gcc-14
CUDA_VISIBLE_DEVICES=0,1
CUDA_VISIBLE_DEVICES=0,1
LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:/usr/local/cuda-12.8/lib64:/usr/local/cuda-12.8/lib64:/usr/local/cuda-12.8/lib64:/usr/local/cuda-12.8/lib64:
CUDA_HOME=/usr/local/cuda-12.8
CUDA_HOME=/usr/local/cuda-12.8
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_turbo2ltr
```

</details>

### 🐛 Describe the bug

I'm running the v1.5.0 prebuilt wheel on Ubuntu 26.04 LTS (Resolute Raccoon) with glibc 2.41 and hitting compilation failures when vLLM tries to JIT compile tilelang kernels at startup.

Error:
```
/usr/include/x86_64-linux-gnu/bits/mathcalls.h(83): error: exception specification is incompatible with that of previous function "cospi" (declared at line 2601 of /usr/local/cuda-12.8/bin/../targets/x86_64-linux/include/crt/math_functions.h)
/usr/include/x86_64-linux-gnu/bits/mathcalls.h(85): error: exception specification is incompatible with that of previous function "sinpi"
/usr/include/x86_64-linux-gnu/bits/mathcalls.h(206): error: exception specification is incompatible with that of previous function "rsqrt"
(same for cospif, sinpif, rsqrtf)
6 errors detected in the compilation of tvm_kernels.cu
```

The nvcc command tilelang is invoking:
```
/usr/local/cuda-12.8/bin/nvcc --cubin -O3 -lineinfo -arch=sm_70 -std=c++20 \
  -I.../tilelang/3rdparty/../src \
  -I.../tilelang/3rdparty/cutlass/include \
  -o /tmp/xxx/tvm_kernels.cubin /tmp/xxx/tvm_kernels.cu
```

What I tried:

Set `CC=gcc-14`, `CXX=g++-14`, `CUDAHOSTCXX=gcc-14`
Set `CUDA_HOME`, `PATH`, `LD_LIBRARY_PATH` correctly
Applied the `sed -i '5994d;6014d'` patch from issue #215 — did not help, errors come from bits/mathcalls.h not the patched file
`CUDA_VISIBLE_DEVICES=0,1 CUDA_DEVICE_ORDER=PCI_BUS_ID` to restrict to V100s

Issue #215 describes a similar problem for source builds on Debian 13 / glibc 2.41, but the sed workaround there targets math_functions.h lines 5994/6014 (sincospi/sincospif). My errors with the prebuilt wheel come from bits/mathcalls.h conflicting with different lines in math_functions.h (cospi, sinpi, rsqrt). The patch doesn't resolve it.

The model loads fine (weights load to VRAM correctly, both V100s show 18.2GB used), and everything works until tilelang tries to JIT compile the GDN prefill kernels.

Is there a known workaround for the prebuilt wheel on Ubuntu 26.04, or would a source build with the #215 patch be the recommended path?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.
